name: Build and Push 

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/adservice/
          push: true
          tags: neurofunkbeat/microservicedemo:adservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/cartservice/src/
          push: true
          tags: neurofunkbeat/microservicedemo:cartservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/checkoutservice/
          push: true
          tags: neurofunkbeat/microservicedemo:checkoutservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/currencyservice/
          push: true
          tags: neurofunkbeat/microservicedemo:currencyservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/emailservice/
          push: true
          tags: neurofunkbeat/microservicedemo:emailservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/frontend/
          push: true
          tags: neurofunkbeat/microservicedemo:frontend
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/loadgenerator/
          push: true
          tags: neurofunkbeat/microservicedemo:loadgenerator
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/paymentservice/
          push: true
          tags: neurofunkbeat/microservicedemo:paymentservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/productcatalogservice/
          push: true
          tags: neurofunkbeat/microservicedemo:productcatalogservice
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/productcatalogservice/
          push: true
          tags: neurofunkbeat/microservicedemo:productcatalogservice    
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/recommendationservice/
          push: true
          tags: neurofunkbeat/microservicedemo:recommendationservice         
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/shippingservice/
          push: true
          tags: neurofunkbeat/microservicedemo:shippingservice
          


          
       
    
        
